import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/_home.module.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      </main>
      <div className="container">
      <div className="content">
        <h1 className="h1">Turn ideas into solutions</h1>
        <h2 className="h2">Electrify you customer mind.</h2>
        <Link href="/solutions" className="button">Solutions</Link>
      </div>
    </div>
    </>
  );
}
